### PR TITLE
Entry exit analytics availability date change

### PR DESCRIPTION
**Pull request by vinayd-msft**

### CODE REVIEW

**Comment by vinayd-msft** [comment]
@alfergus Can we please also add a statement to this change: "These details are available for journeys published (or updated) after the preview is enabled. "  I am not sure how to recall and update the PR.

**Comment by colinbirkett** [comment]
Hi @vinayd-msft and @bishalgoswami, I can do the change but I need to know what the specific 'details' are you are referring to. Where in the change do you want to include the additional statement? At the end? Just want to get this accurate.

**Comment by vinayd-msft** [comment]
Should be at the end, I expanded "These details" based on your feedback. The updated note will read like this:

Entry and exit details are in preview. If you don't see these details, go to **Settings** > **Feature switches** > **Journey** and enable the "Tile entry and exit analytics (preview)" feature switch. This feature is currently available for one-time journeys with static audience. Support for repeating journeys is planned by December 16, 2024. Support for Ongoing journeys will be available in Feb 2025 release. Entry and exit details are available for journeys published (or updated) after the preview is enabled.

**Comment by alfergus** [comment]
> Should be at the end, I expanded "These details" based on your feedback. The updated note will read like this:
> 
> Entry and exit details are in preview. If you don't see these details, go to **Settings** > **Feature switches** > **Journey** and enable the "Tile entry and exit analytics (preview)" feature switch. This feature is currently available for one-time journeys with static audience. Support for repeating journeys is planned by December 16, 2024. Support for Ongoing journeys will be available in Feb 2025 release. Entry and exit details are available for journeys published (or updated) after the preview is enabled.

I went ahead and updated this. Thanks, Vinay!

**Pull request merged**
